# Docker Compose override for scaling services independently
# Usage: docker-compose -f docker-compose.yml -f docker-compose.scale.yml up -d

version: "3.9"
services:
  # Scale Alert Trigger Service to 3 instances
  alert-trigger-service:
    deploy:
      replicas: 3
    environment:
      - USER_SERVICE_BASE_URL=http://user-service:8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ALERT_THRESHOLD_PERCENT=80
      - SERVER_PORT=8082

  # Scale Notification Service to 2 instances (Kafka consumer group will distribute load)
  notification-service:
    deploy:
      replicas: 2
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=notification-service
      - SERVER_PORT=8083
    # No port mapping - services communicate internally via Docker network
    # Only one instance will be accessible externally via the base docker-compose.yml

    # Scale User Service to 2 instances with load balancing
  user-service:
    deploy:
      replicas: 2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/telco
      - SPRING_DATASOURCE_USERNAME=telco
      - SPRING_DATASOURCE_PASSWORD=telco
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081
