# Staging Environment
version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: telco_staging
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: telco_staging
    ports:
      - "5432:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U telco_staging" ]
      interval: 10s
      timeout: 5s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  user-service:
    image: telco-registry/user-service:${IMAGE_TAG:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telco_staging
      SPRING_DATASOURCE_USERNAME: telco_staging
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  alert-trigger-service:
    image: telco-registry/alert-trigger-service:${IMAGE_TAG:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: staging
      USER_SERVICE_BASE_URL: http://user-service:8081/api/v1
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ALERT_THRESHOLD_PERCENT: 80
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - kafka
    restart: unless-stopped

  notification-service:
    image: telco-registry/notification-service:${IMAGE_TAG:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: staging
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_GROUP_ID: notification-service
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    restart: unless-stopped

volumes:
  postgres_staging_data:
