apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: telco-system
  labels:
    app: notification-service
spec:
  replicas: 2  # Start with 2 replicas
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: notification-service
        image: telco/notification-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: telco-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_CONSUMER_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: telco-config
              key: KAFKA_CONSUMER_GROUP_ID
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: telco-config
              key: NOTIFICATION_SERVICE_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: telco-system
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: telco-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
